version: 2
jobs:
  test:
    docker:
      - image: ehdevops/ruby240:latest
    working_directory: ~/xero_gateway
    steps:
      - checkout
      - restore_cache:
          name: Restore Gem Dependencies from Cache
          keys:
            - bundle-caches{{ checksum "Gemfile" }}
      - run: bundle check || bundle install --jobs=4 --retry=3
      - save_cache:
          key: bundle-caches{{ checksum "Gemfile" }}
          paths:
            - ~/xero_gateway/vendor/bundle
      - run: rake test

  publish:
    docker:
      - image: ehdevops/ruby240:latest
    working_directory: ~/xero_gateway
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-caches{{ checksum "app.json" }}
      - run: bundle check || bundle install --jobs=4 --retry=3
      - save_cache:
          key: bundle-caches{{ checksum "app.json" }}
          paths:
            - ~/xero_gateway/vendor/bundle
      - run:
        name: Deploy to gemfury
        command: |
          if [ $CIRCLE_BRANCH == 'master' ]
          then
            bundle exec ruby scripts/publish.rb
          else
            bundle exec ruby scripts/publish_staging.rb $CIRCLE_SHA1
          fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - publish:
          context: org-global
          filters:
            branches:
              only:
                - master
                - staging
          requires:
            - test
